declare module "graphql-type-datetime";
declare module "minify-graphql-loader";
declare module "redis-dataloader";
declare module "khong-dau";
declare module "wink-bm25-text-search";
declare module "wink-nlp-utils";
declare module "rsa-pem-from-mod-exp";
declare module "@jtfell/lru-map";
declare module "written-number";
